### PR TITLE
rgb dimmer: save default color brightness

### PR DESCRIPTION
**Pull request by wurststulle**
this adds a new message type for saving the default color and brightness to eeprom. this PR contains all changes from https://github.com/breaker27/smarthomatic/pull/133

### CODE REVIEW

**Comment by breaker27** [comment]
What's the use case for a default color? Typically, the RGB dimmer is connected to a power supply and the rest is controlled via e.g. FHEM.

**Comment by breaker27** [comment]
There is definitely no need for a new message type!

**Comment by wurststulle** [comment]
There is no functionality to save stuff to the eeprom. If you dont want to
save it every time (with e.g. set) wie neues a new one.
Am 26.02.2015 20:37 schrieb "breaker27" <notifications@github.com>:

**Comment by breaker27** [comment]
I think there would be two values: The one is the (normal) color (immediately shown when set), the other value would be the default color (immediately written to e2p, but not shown). I don't see a use case to set the default color without saving it to e2p.

**Pull request closed without merging**
