### PR TITLE
Rgb dimmer: completely deactivate leds and add brightness message

### PR DESCRIPTION
**Pull request by wurststulle**
- disable COM0A1 and COM0B1 when value is 0 to deactivate the leds completely
- add message to set the brightness of the rgb dimmer

### CODE REVIEW

**Comment by breaker27** [comment]
1) How is the behavior when brightness is set? Do I understand it correctly that it is an additional factor? So I may set color "white" and can dim it with brightness or can set "yellow" and dim it with brightness?

2) What is the advantage turning COM0A1 and COM0B1 off? If the threshold for the timers is 0, the pins should be off already, right? Isn't this only additional (unnecessary) code?

**Comment by wurststulle** [comment]
1) yes.
2) no. When the timer is 0, the led is still in. With minimal intensity,
but on. Turning both off will turn the leds off completely.
Am 14.02.2015 19:35 schrieb "breaker27" <notifications@github.com>:

**Comment by wurststulle** [comment]
1) its working fine for blue, i dont know why.
2) i am fine with both, not sure whats the better solution.

**Comment by breaker27** [comment]
I fixed the bug that the LEDs are not completely off with color 0 (see https://github.com/breaker27/smarthomatic/commit/c56586adc180563274ef0da86f03ecb372bbe9f6). This is for the 0.9.0. For the brightness feature, I'll look at it later (>0.9.0).

**Comment by wurststulle** [comment]
This will fix the issue at 0% duty cycle. But now you have it at 100%. So it will jump between 99 and 100%. This is imho even worse.

**Comment by breaker27** [comment]
What do you mean with "jump"? I tested several colors (incl. white) and see no problem. What do I have to set as color or animation that I will see an issue?

**Comment by wurststulle** [comment]
In fact i dont like it when something is supposed to be off but is still in for some time. Imagine you are using something else then leds, e.g. a fan. I dont know if it is a problem, but it does not feel right.

**Comment by breaker27** [comment]
I've to correct the times I mentioned. It is 8µs for both inverting and non-inverting mode with 480 Hz PWM. The rest is correct.

You write in the last message that something should not be on when it's supposed to be off.
But this is also not the case anymore after the fix! When OCR0A is at 255 with inverting PWM mode, the LED is 100% off.

Where do you see a problem? I don't get it.

**Comment by wurststulle** [comment]
when its completely off its ok.
regarding the 100%:
with the non inverted implementation, you got spikes at 0% duty cycle. if you invert it, you got them at 100%. i dont know if you see these changes from ~99,4 to 100% and back. i will test it this evening. if you cant see it, lets do it this way.

**Comment by breaker27** [comment]
I solved it by using the phase correct PWM mode (submitted to the develop branch). This creates duty cycles of 0..100%. I didn't integrate it in the 0.9.0 though, because it needs more testing.

**Comment by breaker27** [comment]
Forgot to mention: Brightness message will be added also (separate issue).

**Pull request closed without merging**
